### ISSUE TITLE
Fix the styling for "add image" section of the Languages add and edit forms

### ISSUE THREAD

**Issue by golars497** [dwanderton/cmt#11]
For the Add form:
need to fix styling. Also need to make the input field (which stores image URL) invisble

For the Edit form:
Same as the add form except the image control is unaligned with other form controls as well as being on top of the page

**Comment by dwanderton** [comment]
Input field invisible with commit b893160

**Comment by dwanderton** [comment]
other issues with layout being broken:
<img width="1192" alt="screen shot 2017-08-07 at 00 16 01" src="https://user-images.githubusercontent.com/3466284/29007932-a9cb2dee-7b05-11e7-82f9-db1eff8ed0c3.png">

**Comment by dwanderton** [comment]
Confirmed due to media upload addition: 
<img width="1193" alt="screen shot 2017-08-07 at 00 18 38" src="https://user-images.githubusercontent.com/3466284/29007954-0973579e-7b06-11e7-962a-b0c98938e1b2.png">

**Comment by dwanderton** [comment]
Fixed layout issue on add. 

<img width="1195" alt="screen shot 2017-08-07 at 00 26 54" src="https://user-images.githubusercontent.com/3466284/29008027-5e5e5bea-7b07-11e7-99c2-e9a9ac3b5564.png">
