### ISSUE TITLE
About section doesn't filter for category about

### ISSUE THREAD

**Issue by dwanderton** [dwanderton/cmt#14]
@golars497 this currently just displays the most recent post. Important to double check all your expectations of functionality - similar to the industry image sizing. test your code like you believe it doesn't work 😉

**Comment by dwanderton** [comment]
<img width="341" alt="screen shot 2017-08-07 at 03 08 19" src="https://user-images.githubusercontent.com/3466284/29009728-b2f22e46-7b1d-11e7-8127-5c3d9fc77ee5.png">

I believe this happens because when the category doesnt exist 0 is returned

**Comment by dwanderton** [comment]
confirmed. No straightforward fix - but should be considered a bug.

**Comment by golars497** [comment]
Hi David, for me
1. it would display nothing if I don't have a post with "about" category.
2. it would display the latest post with the about category (e.g. if there are 2 posts with the about category)

**Comment by dwanderton** [comment]
I think it would display nothing as you had no other posts at the time. (just a guess)

**Comment by dwanderton** [comment]
Same behaviour on staging site.
