### ISSUE TITLE
Small typo on main page

### ISSUE THREAD

**Issue by dwanderton** [dwanderton/cmt#3]
<img width="288" alt="screen shot 2017-07-23 at 13 13 17" src="https://user-images.githubusercontent.com/3466284/28501371-b724538e-6fa8-11e7-93a4-b4c0acb358f8.png">

**Comment by dwanderton** [comment]
In best practice these titles could be auto generated by existing post types? Industries, Services etc...

**Comment by golars497** [comment]
We can do that I think, but what about the Language Taxonomy? I guess it would be: Generate Based on Post Types, then Generate Based on Taxonomies?

**Comment by dwanderton** [comment]
No need to pursue it - I was just thinking about in 'a perfect world' :)

**Comment by golars497** [comment]
I always pursue anything that save lines of code hahaha
